---
spring:
  profiles:
    active: cloud
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/company-db
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: cloud
  jpa:
    hibernate:
      ddl-auto: update
